spring.application.name=Orbia

spring.datasource.url=jdbc:mysql://localhost:3306/agend
spring.datasource.username=root
spring.datasource.password=root

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080